[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]

[logger]
level = "info"

[runner]
fastReruns = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[global]
dataFrameSerialization = "arrow"
